// Integrity of the committed-but-NOT-yet-pinned conformance manifests
// (staging mechanism cinatra#3156, epic cinatra#3155).
//
// A PINNED manifest's bytes are locked twice over: tests/e2e/design/conformance-pins.json
// records `manifestSha256`, and both scripts/design/check-conformance-testids.mjs
// and the functional-acceptance suite's "spec pin integrity" test refuse a committed
// copy that does not hash to it. That is what makes "the committed copies are the
// verbatim generated bytes, never hand-edited" a CHECKED claim rather than a note.
//
// An UNPINNED manifest has no pin, so none of those checks reach it. A drawing is
// staged under manifests/ while its surfaces are driven one wave at a time, and for
// the whole of that window its bytes are unverified: the file could be hand-edited,
// truncated, or silently diverge from the published artifact it claims to copy, and
// every gate would stay green. loadUnpinnedManifests() would keep generating a suite
// against it, and check-conformance-testids.mjs would keep accepting testid-contract
// and allowlist entries naming surfaces the published artifact may no longer declare.
//
// This file closes that window. Every committed manifest is either PINNED (checked
// elsewhere) or STAGED and recorded here with the sha256 of the published artifact it
// was copied from — so a staged file cannot be edited, and a manifest cannot be added
// without its bytes being recorded. When a drawing earns its pin, its entry moves from
// STAGED into conformance-pins.json and is deleted here.

import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, "..", "..", "..");
const CONF_DIR = path.join(REPO_ROOT, "tests", "e2e", "design", "conformance");
const MANIFEST_DIR = path.join(CONF_DIR, "manifests");

const readJson = (p) => JSON.parse(readFileSync(p, "utf8"));
const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");

/**
 * The manifests committed under manifests/ that conformance-pins.json
 * deliberately does not name yet, each with the published artifact it is a
 * verbatim copy of.
 *
 * `manifestSha256` is the sha256 of the published bytes; `contentHash` is the
 * manifest's own embedded spec-source hash. Both are recorded the same way a pin
 * records them, and for the same reason: a claim about which drawing this repo is
 * grading against has to name the exact bytes it held against.
 */
const STAGED = {
  // The artifacts drawing, adopted at the ratification that made the entity-page
  // tablist the five-entry strip and added the workspace scope (epic cinatra#2806).
  // Unpinned because only one of its surfaces is in scope for that adoption; it
  // joins the pin gate when every surface of the drawing has a driver.
  "app-artifacts.json": {
    spec: "specs/app-artifacts.html",
    manifestSha256: "555413acbeb45f943a39cdcaba4fce519d51eaddbbf2338f875a54033c5933a0",
    contentHash: "sha256:c6cad4b9f61f50ecccb3185913afa0f400a41ca6f06327ab57fcbcda68f1e563",
  },
  // The lifecycle-cards drawing, staged by cinatra#3156 (the suggestion-chip wave).
  "app-lifecycle-cards.json": {
    spec: "specs/app-lifecycle-cards.html",
    manifestSha256: "983fd9fdaa49f4d0749c4637c2ede51ce0b0cd1dc858a92e4d7e63080a4e6af3",
    contentHash: "sha256:218bf86ae8e105d9279aaf8f6e8ecfc8612ec70b5f7d982aecd94491f728ca10",
  },
};

const pins = readJson(path.join(CONF_DIR, "..", "conformance-pins.json"));
const pinnedFiles = new Set(pins.manifests.map((pin) => pin.file));
const committedFiles = readdirSync(MANIFEST_DIR)
  .filter((f) => f.endsWith(".json"))
  .sort();

describe("committed conformance manifests are all accounted for", () => {
  it("every committed manifest is either pinned or recorded as staged", () => {
    const unaccounted = committedFiles.filter(
      (f) => !pinnedFiles.has(f) && STAGED[f] === undefined,
    );
    expect(
      unaccounted,
      `manifests/${unaccounted.join(", ")} is committed but neither pinned in conformance-pins.json nor recorded in STAGED — an unpinned manifest whose bytes nothing checks can be hand-edited without a single gate turning red. Record it here with the sha256 of the published artifact it copies, or pin it.`,
    ).toEqual([]);
  });

  it("no manifest is both pinned and staged", () => {
    const both = Object.keys(STAGED).filter((f) => pinnedFiles.has(f));
    expect(
      both,
      `manifests/${both.join(", ")} is pinned AND recorded as staged — a pinned manifest is checked by conformance-pins.json; delete the STAGED entry so one record owns it.`,
    ).toEqual([]);
  });
});

describe.each(Object.entries(STAGED))("staged manifest %s", (file, expected) => {
  const abs = path.join(MANIFEST_DIR, file);

  it("is committed under manifests/", () => {
    expect(
      existsSync(abs),
      `manifests/${file} is recorded as staged but is not committed — add the verbatim published artifact or drop the STAGED entry.`,
    ).toBe(true);
  });

  it("is the verbatim published artifact (bytes and embedded content hash)", () => {
    const bytes = readFileSync(abs);
    expect(
      sha256(bytes),
      `STAGED INTEGRITY: manifests/${file} does not hash to the recorded manifestSha256 — the committed copy must be the VERBATIM generated artifact, never hand-edited. Re-copy it from the published conformance artifact and update this record in the same commit.`,
    ).toBe(expected.manifestSha256);

    const manifest = JSON.parse(bytes.toString("utf8"));
    expect(manifest.schemaVersion).toBe("1.0.0");
    expect(manifest.spec).toBe(expected.spec);
    expect(
      manifest.contentHash,
      `STAGED INTEGRITY: manifests/${file} embeds a different contentHash than recorded — the record no longer names the drawing bytes this manifest was generated from.`,
    ).toBe(expected.contentHash);
    expect(manifest.surfaces.length).toBeGreaterThan(0);
  });
});

describe("the artifacts drawing carries the ratified five-entry tab strip", () => {
  // The adoption this manifest was staged for (epic cinatra#2806): the entity-page
  // tablist became Dashboards | Assistants | Agents | Artifacts | Skills, with
  // Settings appended last only where a scope has a settings pane. The strip itself
  // is drawn in the ratified drawing; what the manifest carries is the surface
  // contract the product must eventually drive. Asserting it here means a later
  // regeneration that quietly drops the amendment cannot land unnoticed while the
  // drawing is still unpinned.
  // Read at assertion time, not at module load: a missing manifest must fail THIS
  // describe with its own message rather than crash the whole file before the
  // staging records above get a chance to say what is wrong.
  const scopeDashboardsTab = () => {
    const abs = path.join(MANIFEST_DIR, "app-artifacts.json");
    expect(
      existsSync(abs),
      "manifests/app-artifacts.json is not committed — the artifacts drawing has not been adopted, so the amended tablist surface cannot be checked.",
    ).toBe(true);
    const surface = readJson(abs).surfaces.find((s) => s.id === "scope-dashboards-tab");
    expect(
      surface,
      "app-artifacts.json no longer declares scope-dashboards-tab — the amended entity-page tablist surface is the reason this manifest was adopted.",
    ).toBeDefined();
    return surface;
  };

  it("declares the scope-dashboards-tab surface", () => {
    expect(scopeDashboardsTab().id).toBe("scope-dashboards-tab");
  });

  it("binds the scope name to the identity display name", () => {
    expect(scopeDashboardsTab().fields).toEqual([
      { field: "name", source: "identity.displayName" },
    ]);
  });

  it("declares the add-picker, open and remove actions with their outcomes", () => {
    expect(scopeDashboardsTab().actions).toEqual([
      { action: "open-add-picker", outcome: "add-picker-open" },
      { action: "open-dashboard", outcome: "dashboard-canonical" },
      { action: "remove-listing", outcome: "listing-removed" },
    ]);
  });

  it("declares the empty, error, artifact-kind and loading state variants", () => {
    expect(scopeDashboardsTab().states).toEqual(["empty", "error", "kind:artifact", "loading"]);
  });
});

describe("the shrink-only allowlist absorbs no staged surface", () => {
  it("names no surface of a staged manifest", () => {
    const allowlist = readJson(path.join(CONF_DIR, "allowlist.json")).allow;
    const stagedSurfaces = new Set();
    for (const file of Object.keys(STAGED)) {
      const abs = path.join(MANIFEST_DIR, file);
      if (!existsSync(abs)) continue;
      for (const s of readJson(abs).surfaces) stagedSurfaces.add(s.id);
    }
    const absorbed = allowlist.map((e) => e.surface).filter((s) => stagedSurfaces.has(s));
    expect(
      absorbed,
      `allowlist.json exempts ${absorbed.join(", ")}, a surface of a STAGED manifest. A staged drawing needs no exemption: an unpinned surface with no driver simply generates no test, and the allowlist is shrink-only — it may not gain an entry to absorb a newly adopted drawing.`,
    ).toEqual([]);
  });
});
