/**
 * Pinned conformance-manifest loader for the functional-acceptance suite
 * (cinatra#985).
 *
 * The manifests are GENERATED artifacts of the annotated design specs
 * (cinatra-ai/design, design#19 L2a) published under
 * docs.cinatra.ai/references/design/conformance/. This repo verifies against
 * an EXACT pinned artifact (spec-pins.json):
 *
 *   - The committed copies under manifests/ are the verbatim generated bytes
 *     (never hand-edited); `manifestSha256` locks them — any local edit is a
 *     PIN INTEGRITY red.
 *   - `specContentHash` locks the manifest's embedded spec-source hash, so a
 *     verification claim always names the exact spec bytes it held against.
 *   - While `source` is "repo" (pre-publication fallback), the suite reads
 *     only the committed copy. Flipping `source` to "published" additionally
 *     activates the upstream-drift check (fetch + byte-hash compare) — no
 *     code change involved.
 *
 * Test GENERATION reads the committed copy in both modes (deterministic test
 * lists need synchronous data); the published fetch is a runtime assertion.
 */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";

export type ManifestField = { field: string; source: string };
export type ManifestAction = { action: string; outcome: string };
export type ManifestSurface = {
  id: string;
  fields: ManifestField[];
  actions: ManifestAction[];
  states: string[];
};
export type ConformanceManifest = {
  schemaVersion: string;
  spec: string;
  contentHash: string;
  surfaces: ManifestSurface[];
};

export type SpecPin = {
  id: string;
  file: string;
  source: "repo" | "published";
  manifestSha256: string;
  specContentHash: string;
};

export type SpecPins = {
  publishedBaseUrl: string;
  manifests: SpecPin[];
};

export type PinnedManifest = {
  pin: SpecPin;
  publishedUrl: string;
  /** sha256 (hex) of the committed manifest bytes. */
  repoSha256: string;
  manifest: ConformanceManifest;
};

const CONFORMANCE_DIR = __dirname;

export function sha256Hex(bytes: Buffer | Uint8Array | string): string {
  return createHash("sha256").update(bytes).digest("hex");
}

export function loadSpecPins(): SpecPins {
  const raw = readFileSync(path.join(CONFORMANCE_DIR, "spec-pins.json"), "utf8");
  return JSON.parse(raw) as SpecPins;
}

export function loadAllowlist(): Array<{ manifest: string; surface: string; reason: string }> {
  const raw = readFileSync(path.join(CONFORMANCE_DIR, "allowlist.json"), "utf8");
  return (JSON.parse(raw) as { allow: Array<{ manifest: string; surface: string; reason: string }> }).allow;
}

/**
 * Load every pinned manifest from the committed copies. Parsing is done at
 * test-generation time; pin INTEGRITY (hash equality) is asserted by the
 * suite's dedicated "spec pin" tests so a mismatch is a distinct, actionable
 * red rather than a config crash.
 */
export function loadPinnedManifests(pins: SpecPins): PinnedManifest[] {
  return pins.manifests.map((pin) => {
    const bytes = readFileSync(path.join(CONFORMANCE_DIR, "manifests", pin.file));
    const manifest = JSON.parse(bytes.toString("utf8")) as ConformanceManifest;
    return {
      pin,
      publishedUrl: `${pins.publishedBaseUrl}${pin.file}`,
      repoSha256: sha256Hex(bytes),
      manifest,
    };
  });
}
