/**
 * Pinned conformance-manifest loader for the functional-acceptance suite
 * (cinatra#985).
 *
 * The manifests are GENERATED artifacts of the annotated design specs
 * (the design-system source of truth, L2a) published under
 * docs.cinatra.ai/references/design/conformance/. This repo verifies against
 * an EXACT pinned artifact (../conformance-pins.json):
 *
 *   - The committed copies under manifests/ are the verbatim generated bytes
 *     (never hand-edited); `manifestSha256` locks them — any local edit is a
 *     PIN INTEGRITY red.
 *   - `specContentHash` locks the manifest's embedded spec-source hash, so a
 *     verification claim always names the exact spec bytes it held against.
 *   - While `source` is "repo" (pre-publication fallback), the suite reads
 *     only the committed copy. Flipping `source` to "published" additionally
 *     activates the upstream-drift check (fetch + byte-hash compare) — no
 *     code change involved.
 *
 * Test GENERATION reads the committed copy in both modes (deterministic test
 * lists need synchronous data); the published fetch is a runtime assertion.
 */
import { createHash } from "node:crypto";
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";

export type ManifestField = { field: string; source: string };
export type ManifestAction = { action: string; outcome: string };
export type ManifestSurface = {
  id: string;
  fields: ManifestField[];
  actions: ManifestAction[];
  states: string[];
};
export type ConformanceManifest = {
  schemaVersion: string;
  spec: string;
  contentHash: string;
  surfaces: ManifestSurface[];
};

export type SpecPin = {
  id: string;
  file: string;
  source: "repo" | "published";
  manifestSha256: string;
  specContentHash: string;
};

export type SpecPins = {
  publishedBaseUrl: string;
  manifests: SpecPin[];
};

export type PinnedManifest = {
  pin: SpecPin;
  publishedUrl: string;
  /** sha256 (hex) of the committed manifest bytes. */
  repoSha256: string;
  manifest: ConformanceManifest;
};

const CONFORMANCE_DIR = __dirname;

export function sha256Hex(bytes: Buffer | Uint8Array | string): string {
  return createHash("sha256").update(bytes).digest("hex");
}

export function loadSpecPins(): SpecPins {
  const raw = readFileSync(path.join(CONFORMANCE_DIR, "..", "conformance-pins.json"), "utf8");
  return JSON.parse(raw) as SpecPins;
}

/**
 * Allowlist entry (shrink-only ratchet). WITHOUT `aspects`: the whole surface
 * is exempt (pre-#986 shape). WITH `aspects` (cinatra#986): ONLY the named
 * aspects — "field:<name>" / "action:<name>" / "state:<state>" — are exempt;
 * every other annotated field/action/state on the surface requires an
 * assertion (no-assertion = uncovered = red).
 */
export type AllowlistEntry = {
  manifest: string;
  surface: string;
  aspects?: string[];
  reason: string;
};

export function loadAllowlist(): AllowlistEntry[] {
  const raw = readFileSync(path.join(CONFORMANCE_DIR, "allowlist.json"), "utf8");
  return (JSON.parse(raw) as { allow: AllowlistEntry[] }).allow;
}

/**
 * Load every pinned manifest from the committed copies. Parsing is done at
 * test-generation time; pin INTEGRITY (hash equality) is asserted by the
 * suite's dedicated "spec pin" tests so a mismatch is a distinct, actionable
 * red rather than a config crash.
 */
export function loadPinnedManifests(pins: SpecPins): PinnedManifest[] {
  return pins.manifests.map((pin) => {
    const bytes = readFileSync(path.join(CONFORMANCE_DIR, "manifests", pin.file));
    const manifest = JSON.parse(bytes.toString("utf8")) as ConformanceManifest;
    return {
      pin,
      publishedUrl: `${pins.publishedBaseUrl}${pin.file}`,
      repoSha256: sha256Hex(bytes),
      manifest,
    };
  });
}

/**
 * Load every committed manifest that is NOT yet pinned (cinatra#3156).
 *
 * A drawing joins the pin gate only when EVERY one of its surfaces is covered
 * (epic cinatra#3155 — independent pinning). Coverage, though, is landed one
 * wave at a time, so between the first wave and the pin there is a manifest
 * whose committed bytes are the contract the drivers are written against and
 * which conformance-pins.json deliberately does not name yet.
 *
 * This reads exactly those files: the directory listing minus the pinned ones.
 * It ADDS a reading; it changes nothing about the pinned set. The pinned gate
 * keeps meaning what it has always meant — a PINNED manifest surface with no
 * driver and no allowlist entry is red, full stop — and an unpinned manifest is
 * not a staged-adoption mechanism inside the pin format: it is a file on its way
 * to one, whose already-written drivers run so a wave can prove itself before
 * the pin exists to prove it.
 *
 * Sorted by file name so the generated test list is deterministic.
 */
export function loadUnpinnedManifests(pins: SpecPins): PinnedManifest["manifest"][] {
  const dir = path.join(CONFORMANCE_DIR, "manifests");
  const pinnedFiles = new Set(pins.manifests.map((pin) => pin.file));
  return readdirSync(dir)
    .filter((file) => file.endsWith(".json") && !pinnedFiles.has(file))
    .sort()
    .map((file) => JSON.parse(readFileSync(path.join(dir, file), "utf8")) as ConformanceManifest);
}
