// gen-nango-env.mjs — narrow Nango container env generator (cinatra#1691).
//
// WHY THIS EXISTS
// The nango-server docker service encrypts its stored provider secrets with
// NANGO_ENCRYPTION_KEY. The compose file MUST NOT read that secret via
// `environment: NANGO_ENCRYPTION_KEY: "${NANGO_ENCRYPTION_KEY}"` because that
// interpolation resolves the *shell* env (empty on a bare `docker compose
// up`) AND an empty `environment:` value OVERRIDES an `env_file` value on the
// same key — so Nango silently initializes an UNENCRYPTED store (fresh DB) or
// crashes with the misleading "key has been removed" error (existing DB).
// The fix sources the key from a NARROW generated file
// (docker/nango/.nango.env) referenced via `env_file`, with NO overlapping
// `environment:` mapping (the gen-wayflow-env precedent).
//
// These tests pin:
//  1. buildNangoEnv extracts EXACTLY the nango key and reports it missing
//     (no defaults — it is a secret).
//  2. serializeDotenv emits bare KEY=VALUE the compose env_file parser accepts.
//  3. parseDotenv strips quotes (parity with gen-wayflow-env/check-services).
//  4. overlayProcessEnv: non-empty process value wins; empty never clobbers.
//  5. THE COMPOSE NO-OVERLAP INVARIANT: the nango-server service references
//     docker/nango/.nango.env via env_file (required:false) and its
//     `environment:` block does NOT name NANGO_ENCRYPTION_KEY (else the
//     empty-override trap recurs), while the static wiring stays inline.

import { describe, it, expect } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import {
  parseDotenv,
  buildNangoEnv,
  serializeDotenv,
  overlayProcessEnv,
  shouldPreserveExisting,
} from "../gen-nango-env.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../..");

describe("gen-nango-env — parseDotenv", () => {
  it("parses KEY=VALUE and strips surrounding quotes", () => {
    const env = parseDotenv('A=1\nNANGO_ENCRYPTION_KEY="k-123"\n# comment\nBAD LINE\n');
    expect(env).toEqual({ A: "1", NANGO_ENCRYPTION_KEY: "k-123" });
  });
});

describe("gen-nango-env — buildNangoEnv", () => {
  it("extracts exactly NANGO_ENCRYPTION_KEY (ignores everything else)", () => {
    const { env, missing } = buildNangoEnv({
      NANGO_ENCRYPTION_KEY: "k-123",
      BETTER_AUTH_SECRET: "never",
      OPENAI_API_KEY: "never",
      PORT: "3000",
    });
    expect(env).toEqual({ NANGO_ENCRYPTION_KEY: "k-123" });
    expect(missing).toEqual([]);
  });

  it("reports the key missing when absent or whitespace-only (no default — it is a secret)", () => {
    expect(buildNangoEnv({}).missing).toEqual(["NANGO_ENCRYPTION_KEY"]);
    expect(buildNangoEnv({ NANGO_ENCRYPTION_KEY: "   " }).missing).toEqual([
      "NANGO_ENCRYPTION_KEY",
    ]);
  });

  it("trims surrounding whitespace from a kept value", () => {
    expect(buildNangoEnv({ NANGO_ENCRYPTION_KEY: "  k-1  " }).env).toEqual({
      NANGO_ENCRYPTION_KEY: "k-1",
    });
  });
});

describe("gen-nango-env — overlayProcessEnv", () => {
  it("a non-empty process-env value wins over the file", () => {
    const merged = overlayProcessEnv(
      { NANGO_ENCRYPTION_KEY: "file-key" },
      { NANGO_ENCRYPTION_KEY: "proc-key" },
    );
    expect(merged.NANGO_ENCRYPTION_KEY).toBe("proc-key");
  });

  it("an empty/whitespace process value never clobbers a file value", () => {
    const merged = overlayProcessEnv(
      { NANGO_ENCRYPTION_KEY: "file-key" },
      { NANGO_ENCRYPTION_KEY: "   " },
    );
    expect(merged.NANGO_ENCRYPTION_KEY).toBe("file-key");
  });

  it("never reads keys outside the nango set from the process env", () => {
    const merged = overlayProcessEnv({}, { OPENAI_API_KEY: "sneaky" });
    expect(merged).toEqual({});
  });
});

describe("gen-nango-env — shouldPreserveExisting (tolerant-mode clobber guard, codex 1691-r2)", () => {
  it("preserves an existing file that still carries a non-empty key", () => {
    expect(shouldPreserveExisting("# header\nNANGO_ENCRYPTION_KEY=old-key\n")).toBe(true);
  });

  it("does NOT preserve an empty/keyless/absent existing file", () => {
    expect(shouldPreserveExisting("# header only\n")).toBe(false);
    expect(shouldPreserveExisting("NANGO_ENCRYPTION_KEY=   \n")).toBe(false);
    expect(shouldPreserveExisting(undefined)).toBe(false);
  });
});

describe("gen-nango-env — serializeDotenv", () => {
  it("emits bare KEY=VALUE lines under the generated header", () => {
    const text = serializeDotenv({ NANGO_ENCRYPTION_KEY: "k-123" });
    expect(text).toContain("NANGO_ENCRYPTION_KEY=k-123\n");
    expect(text).not.toContain('"k-123"');
    expect(text.startsWith("# GENERATED by scripts/gen-nango-env.mjs")).toBe(true);
  });
});

describe("docker-compose nango-server service — no env_file/environment overlap", () => {
  const composePath = path.join(REPO_ROOT, "docker-compose.yml");
  const yaml = fs.existsSync(composePath) ? fs.readFileSync(composePath, "utf8") : "";

  // Extract the `nango-server:` service block (from `  nango-server:` up to
  // the next top-level 2-space-indented service key). No YAML dep — the
  // gen-wayflow-env.test.mjs convention.
  function nangoBlock() {
    const lines = yaml.split("\n");
    const start = lines.findIndex((l) => /^  nango-server:\s*$/.test(l));
    expect(start).toBeGreaterThanOrEqual(0);
    let end = lines.length;
    for (let i = start + 1; i < lines.length; i++) {
      if (/^  [A-Za-z0-9_-]+:\s*$/.test(lines[i])) {
        end = i;
        break;
      }
    }
    return lines.slice(start, end);
  }

  it("references docker/nango/.nango.env via env_file (required:false)", () => {
    const block = nangoBlock().join("\n");
    expect(block).toMatch(/env_file:/);
    expect(block).toMatch(/path:\s*\.\/docker\/nango\/\.nango\.env/);
    expect(block).toMatch(/required:\s*false/);
  });

  it("has NO environment: NANGO_ENCRYPTION_KEY (the empty-override trap), static wiring stays inline", () => {
    const block = nangoBlock();
    const envStart = block.findIndex((l) => /^    environment:\s*$/.test(l));
    const envKeys = [];
    if (envStart >= 0) {
      for (let i = envStart + 1; i < block.length; i++) {
        const line = block[i];
        if (/^    [A-Za-z0-9_-]+:/.test(line) && !/^      /.test(line)) break;
        const m = line.match(/^      ([A-Z0-9_]+):/);
        if (m) envKeys.push(m[1]);
      }
    }
    expect(envKeys).not.toContain("NANGO_ENCRYPTION_KEY");
    // The static, non-secret wiring must remain inline.
    expect(envKeys).toContain("SERVER_PORT");
    expect(envKeys).toContain("NANGO_DB_HOST");
  });

  it("package.json services script generates the nango env (hard-fail) before compose up", () => {
    const pkg = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "package.json"), "utf8"));
    expect(pkg.scripts.services).toContain("gen-nango-env.mjs --require-encryption-key");
    expect(pkg.scripts.services.indexOf("gen-nango-env.mjs")).toBeLessThan(
      pkg.scripts.services.indexOf("docker compose"),
    );
    // BEFORE `source .env.local` (CodeRabbit 1698-r1): sourcing shell-expands
    // values (a key containing `$…` would be mangled), and the expanded
    // process value would override the raw file value in overlayProcessEnv.
    // The generator parses the file directly, expansion-free.
    expect(pkg.scripts.services.indexOf("gen-nango-env.mjs")).toBeLessThan(
      pkg.scripts.services.indexOf("source .env.local"),
    );
  });
});

// ---------------------------------------------------------------------------
// NANGO_SECRET_KEY fill (cinatra#2501 follow-up).
//
// The Secrets step of the setup wizard is env-managed the moment .env.local
// carries NANGO_SECRET_KEY; without it the screen shows a raw psql read the
// operator must run by hand — which an automated setup cannot do (and must not
// do by eye, because the value is a live API credential). The generator now
// performs THAT EXACT read against the bundled dev Nango and writes the value
// in, once, quietly, and never prints it.
//
// These tests pin, with a FAKE executor (no docker, no psql, no real secret):
//  1. absent/commented/empty key -> the value is written into .env.local;
//  2. the value NEVER appears in any log line (the whole point);
//  3. an existing value — in the file OR in the shell env — is KEPT and the
//     read is not even attempted (idempotent: a second run changes nothing);
//  4. nango-db unreachable / empty / non-key output -> left unset, message on
//     STDERR, and the caller keeps going (the wizard then still shows its
//     manual command);
//  5. a NON-LOCAL NANGO_SERVER_URL is never served the local container's key;
//  6. the LAST `NANGO_SECRET_KEY` line is replaced IN PLACE — commented example
//     line included — because last-stated is the line the app reads;
//  7. `--quiet` silences the status line on stdout.
// ---------------------------------------------------------------------------

import * as os from "node:os";
import {
  NANGO_SECRET_KEY_QUERY,
  hasNangoSecretKey,
  applySecretKeyToEnvLocal,
  fillNangoSecretKey,
} from "../gen-nango-env.mjs";

// UUID-v4 shaped, like every key nango-server accepts — and not a real one.
const FAKE_SECRET = "00000000-0000-4000-8000-000000000000";
const OTHER_FAKE_SECRET = "11111111-1111-4111-8111-111111111111";

function makeEnvLocal(contents) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "gen-nango-env-"));
  const file = path.join(dir, ".env.local");
  fs.writeFileSync(file, contents);
  return file;
}

function recorder() {
  const out = [];
  const err = [];
  return {
    out,
    err,
    log: (m) => out.push(String(m)),
    warn: (m) => err.push(String(m)),
    all: () => out.concat(err).join("\n"),
  };
}

// Every call in this file injects an executor and an empty process env: the
// tests must never reach docker, and must never be steered by the shell that
// happens to run them.
function fill(overrides) {
  return fillNangoSecretKey({ processEnv: {}, log: () => {}, warn: () => {}, ...overrides });
}

describe("gen-nango-env — NANGO_SECRET_KEY read query", () => {
  it("is the EXACT read .env.example and the Secrets screen document", () => {
    expect(NANGO_SECRET_KEY_QUERY).toBe(
      "SELECT secret_key FROM _nango_environments WHERE name='dev' LIMIT 1;",
    );
    const example = fs.readFileSync(path.join(REPO_ROOT, ".env.example"), "utf8");
    expect(example).toContain(NANGO_SECRET_KEY_QUERY);
    // The wizard states the same read in JSX: its quotes are entity-escaped and
    // the statement is wrapped across source lines. Unescape and collapse the
    // whitespace, then pin the WHOLE command — a screen that changed the
    // environment name or dropped `LIMIT 1` must fail this test, which pinning
    // fragments would not catch.
    const page = fs.readFileSync(
      path.join(REPO_ROOT, "src/app/setup/secrets/page.tsx"),
      "utf8",
    );
    const pageText = page
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&amp;/g, "&")
      .replace(/\s+/g, " ");
    expect(pageText).toContain(
      `docker compose exec -T nango-db psql -U nango -d nango -tAc "${NANGO_SECRET_KEY_QUERY}"`,
    );
  });
});

describe("gen-nango-env — hasNangoSecretKey", () => {
  it("is false when absent, commented, or empty (dotenv semantics)", () => {
    expect(hasNangoSecretKey(makeEnvLocal(""))).toBe(false);
    expect(hasNangoSecretKey(makeEnvLocal("# NANGO_SECRET_KEY=\n"))).toBe(false);
    expect(hasNangoSecretKey(makeEnvLocal("#NANGO_SECRET_KEY=abc\n"))).toBe(false);
    expect(hasNangoSecretKey(makeEnvLocal("NANGO_SECRET_KEY=\n"))).toBe(false);
    expect(hasNangoSecretKey(makeEnvLocal("NANGO_SECRET_KEY=   \n"))).toBe(false);
    // An inline comment is dotenv syntax, not a value.
    expect(hasNangoSecretKey(makeEnvLocal("NANGO_SECRET_KEY= # filled by the setup\n"))).toBe(
      false,
    );
    expect(hasNangoSecretKey(makeEnvLocal('NANGO_SECRET_KEY="" # empty\n'))).toBe(false);
    // LAST stated wins — the reader contract the app itself follows.
    expect(hasNangoSecretKey(makeEnvLocal("NANGO_SECRET_KEY=old\nNANGO_SECRET_KEY=\n"))).toBe(
      false,
    );
  });

  it("is true for an uncommented, non-empty value — `export ` included", () => {
    expect(hasNangoSecretKey(makeEnvLocal("NANGO_SECRET_KEY=abc\n"))).toBe(true);
    expect(hasNangoSecretKey(makeEnvLocal("export NANGO_SECRET_KEY=abc\n"))).toBe(true);
    expect(hasNangoSecretKey(makeEnvLocal("A=1\nNANGO_SECRET_KEY = abc \nB=2\n"))).toBe(true);
  });
});

describe("gen-nango-env — applySecretKeyToEnvLocal", () => {
  it("replaces the commented example line IN PLACE (never duplicated)", () => {
    const after = applySecretKeyToEnvLocal("A=1\n# NANGO_SECRET_KEY=\nB=2\n", FAKE_SECRET);
    expect(after).toBe(`A=1\nNANGO_SECRET_KEY=${FAKE_SECRET}\nB=2\n`);
    expect(after.match(/NANGO_SECRET_KEY=/g)).toHaveLength(1);
  });

  it("replaces the LAST key line, because last-stated is what the app reads", () => {
    expect(
      applySecretKeyToEnvLocal("# NANGO_SECRET_KEY=\nNANGO_SECRET_KEY=\n", FAKE_SECRET),
    ).toBe(`# NANGO_SECRET_KEY=\nNANGO_SECRET_KEY=${FAKE_SECRET}\n`);
    expect(applySecretKeyToEnvLocal("export NANGO_SECRET_KEY=\n", FAKE_SECRET)).toBe(
      `NANGO_SECRET_KEY=${FAKE_SECRET}\n`,
    );
  });

  it("appends with a trailing newline when the key is absent entirely", () => {
    expect(applySecretKeyToEnvLocal("A=1\n", FAKE_SECRET)).toBe(
      `A=1\nNANGO_SECRET_KEY=${FAKE_SECRET}\n`,
    );
    expect(applySecretKeyToEnvLocal("A=1", FAKE_SECRET)).toBe(
      `A=1\nNANGO_SECRET_KEY=${FAKE_SECRET}\n`,
    );
  });
});

describe("gen-nango-env — fillNangoSecretKey", () => {
  it("writes the value read from nango-db and NEVER logs it", () => {
    const file = makeEnvLocal("A=1\n# NANGO_SECRET_KEY=\n");
    const rec = recorder();
    const calls = [];
    const result = fill({
      envLocalPath: file,
      exec: (args) => {
        calls.push(args);
        return { ok: true, stdout: `${FAKE_SECRET}\n` };
      },
      log: rec.log,
      warn: rec.warn,
    });

    expect(result.status).toBe("written");
    expect(fs.readFileSync(file, "utf8")).toBe(`A=1\nNANGO_SECRET_KEY=${FAKE_SECRET}\n`);
    expect(rec.all()).not.toContain(FAKE_SECRET);
    expect(rec.out.join("\n")).toContain("NANGO_SECRET_KEY: written");
    // The read is the documented one, run through `docker compose … exec -T nango-db psql`.
    expect(calls).toHaveLength(1);
    expect(calls[0]).toContain("compose");
    expect(calls[0].join(" ")).toContain("exec -T nango-db psql -U nango -d nango -tAc");
    expect(calls[0].at(-1)).toBe(NANGO_SECRET_KEY_QUERY);
  });

  it("writes 0600 and never widens an existing .env.local's mode", () => {
    const file = makeEnvLocal("# NANGO_SECRET_KEY=\n");
    fs.chmodSync(file, 0o600);
    fill({ envLocalPath: file, exec: () => ({ ok: true, stdout: FAKE_SECRET }) });
    expect(fs.statSync(file).mode & 0o777).toBe(0o600);
  });

  it("pins the read to the resolved compose project so a lane reads ITS nango-db", () => {
    for (const line of ["COMPOSE_PROJECT_NAME=lane-x\n", "export COMPOSE_PROJECT_NAME=lane-x # lane\n"]) {
      const calls = [];
      fill({
        envLocalPath: makeEnvLocal(line),
        exec: (args) => {
          calls.push(args);
          return { ok: true, stdout: FAKE_SECRET };
        },
      });
      expect(calls[0].join(" ")).toContain("-p lane-x");
    }
  });

  it("refuses a COMPOSE_PROJECT_NAME compose itself would reject (never trims into another project)", () => {
    for (const stated of [" lane-x ", "Lane-X", "lane x", "-lane"]) {
      const file = makeEnvLocal("# NANGO_SECRET_KEY=\n");
      const rec = recorder();
      const result = fill({
        envLocalPath: file,
        processEnv: { COMPOSE_PROJECT_NAME: stated },
        exec: () => {
          throw new Error("must not run");
        },
        log: rec.log,
        warn: rec.warn,
      });
      expect(result.status).toBe("not-canonical");
      expect(fs.readFileSync(file, "utf8")).toBe("# NANGO_SECRET_KEY=\n");
      expect(rec.err.join("\n")).toContain("left unset");
    }
  });

  it("reads the project the LAUNCHER exports for a file-stated name, not the raw text", () => {
    // scripts/dev-compose-env.mjs resolves .env.local's COMPOSE_PROJECT_NAME
    // through readEnvFileValue and EXPORTS that value into docker's own env —
    // docker never reads .env.local itself. So the parsed value is the project
    // the lane's containers actually run under, and this read must use it.
    const calls = [];
    fill({
      envLocalPath: makeEnvLocal('COMPOSE_PROJECT_NAME=" lane-x "\n# NANGO_SECRET_KEY=\n'),
      exec: (args) => {
        calls.push(args);
        return { ok: true, stdout: FAKE_SECRET };
      },
    });
    expect(calls[0].join(" ")).toContain("-p lane-x");

    // A file value that states nothing leaves the project unpinned — compose
    // derives it from the directory basename, exactly as the launcher does.
    const unscoped = [];
    fill({
      envLocalPath: makeEnvLocal('COMPOSE_PROJECT_NAME="   "\n# NANGO_SECRET_KEY=\n'),
      exec: (args) => {
        unscoped.push(args);
        return { ok: true, stdout: FAKE_SECRET };
      },
    });
    expect(unscoped[0]).not.toContain("-p");
  });

  it("reports write-failed — never throws — when .env.local cannot be replaced", () => {
    const file = makeEnvLocal("# NANGO_SECRET_KEY=\n");
    const dir = path.dirname(file);
    fs.chmodSync(dir, 0o500); // readable, not writable: the temp create fails
    const rec = recorder();
    let result;
    try {
      expect(() => {
        result = fill({
          envLocalPath: file,
          exec: () => ({ ok: true, stdout: FAKE_SECRET }),
          log: rec.log,
          warn: rec.warn,
        });
      }).not.toThrow();
    } finally {
      fs.chmodSync(dir, 0o700);
    }
    expect(result.status).toBe("write-failed");
    expect(fs.readFileSync(file, "utf8")).toBe("# NANGO_SECRET_KEY=\n");
    expect(rec.all()).not.toContain(FAKE_SECRET);
    expect(fs.readdirSync(dir)).toEqual([".env.local"]); // no stray temp file
  });

  it("leaves no temp file behind on a successful write either", () => {
    const file = makeEnvLocal("# NANGO_SECRET_KEY=\n");
    fill({ envLocalPath: file, exec: () => ({ ok: true, stdout: FAKE_SECRET }) });
    expect(fs.readdirSync(path.dirname(file))).toEqual([".env.local"]);
  });

  it("keeps an existing non-empty value and never attempts the read (idempotent)", () => {
    const before = "A=1\nNANGO_SECRET_KEY=already-set\n";
    const file = makeEnvLocal(before);
    const rec = recorder();
    let called = false;
    const result = fill({
      envLocalPath: file,
      exec: () => {
        called = true;
        return { ok: true, stdout: FAKE_SECRET };
      },
      log: rec.log,
      warn: rec.warn,
    });

    expect(result.status).toBe("kept");
    expect(called).toBe(false);
    expect(fs.readFileSync(file, "utf8")).toBe(before);
    expect(rec.out.join("\n")).toContain("NANGO_SECRET_KEY: kept");
  });

  it("keeps a key supplied by the SHELL env (it overrides the file for the app)", () => {
    const before = "# NANGO_SECRET_KEY=\n";
    const file = makeEnvLocal(before);
    const result = fill({
      envLocalPath: file,
      processEnv: { NANGO_SECRET_KEY: "from-the-shell" },
      exec: () => {
        throw new Error("must not run");
      },
    });
    expect(result.status).toBe("kept");
    expect(fs.readFileSync(file, "utf8")).toBe(before);
  });

  it("a second run after a write changes nothing", () => {
    const file = makeEnvLocal("# NANGO_SECRET_KEY=\n");
    expect(
      fill({ envLocalPath: file, exec: () => ({ ok: true, stdout: FAKE_SECRET }) }).status,
    ).toBe("written");
    const afterFirst = fs.readFileSync(file, "utf8");
    expect(
      fill({ envLocalPath: file, exec: () => ({ ok: true, stdout: OTHER_FAKE_SECRET }) }).status,
    ).toBe("kept");
    expect(fs.readFileSync(file, "utf8")).toBe(afterFirst);
  });

  it("never serves a NON-LOCAL Nango the bundled container's key", () => {
    for (const source of [
      { file: "NANGO_SERVER_URL=https://api.nango.example\n# NANGO_SECRET_KEY=\n", env: {} },
      { file: "# NANGO_SECRET_KEY=\n", env: { NANGO_SERVER_URL: "https://api.nango.example" } },
    ]) {
      const file = makeEnvLocal(source.file);
      const rec = recorder();
      const result = fill({
        envLocalPath: file,
        processEnv: source.env,
        exec: () => {
          throw new Error("must not run");
        },
        log: rec.log,
        warn: rec.warn,
      });
      expect(result.status).toBe("not-local");
      expect(fs.readFileSync(file, "utf8")).toBe(source.file);
      expect(rec.err.join("\n")).toContain("not a local Nango — left unset");
    }
  });

  it("leaves the key unset and says so on STDERR when nango-db is not reachable", () => {
    const before = "# NANGO_SECRET_KEY=\n";
    const file = makeEnvLocal(before);
    const rec = recorder();
    const result = fill({
      envLocalPath: file,
      exec: () => ({ ok: false, stdout: "" }),
      log: rec.log,
      warn: rec.warn,
    });

    expect(result.status).toBe("unreachable");
    expect(fs.readFileSync(file, "utf8")).toBe(before);
    expect(rec.err.join("\n")).toContain("nango-db not reachable — left unset");
    expect(rec.out.join("\n")).not.toContain("nango-db not reachable");
  });

  it("treats empty or non-key output as not reachable (psql error text is not a key)", () => {
    for (const stdout of [
      "",
      "   \n",
      "psql: error: no such container\n",
      "ERROR:\n",
      "not-a-uuid\n",
    ]) {
      const file = makeEnvLocal("# NANGO_SECRET_KEY=\n");
      const result = fill({ envLocalPath: file, exec: () => ({ ok: true, stdout }) });
      expect(result.status).toBe("unreachable");
      expect(fs.readFileSync(file, "utf8")).toBe("# NANGO_SECRET_KEY=\n");
    }
  });

  it("an executor that throws is contained (the setup is never failed for this)", () => {
    const file = makeEnvLocal("# NANGO_SECRET_KEY=\n");
    const rec = recorder();
    expect(() =>
      fill({
        envLocalPath: file,
        exec: () => {
          throw new Error("docker not on PATH");
        },
        log: rec.log,
        warn: rec.warn,
      }),
    ).not.toThrow();
    expect(fs.readFileSync(file, "utf8")).toBe("# NANGO_SECRET_KEY=\n");
    expect(rec.err.join("\n")).toContain("nango-db not reachable — left unset");
  });

  it("does not overwrite a key written WHILE the slow docker read was running", () => {
    const file = makeEnvLocal("# NANGO_SECRET_KEY=\n");
    const rec = recorder();
    const result = fill({
      envLocalPath: file,
      exec: () => {
        // The operator finishes the wizard's Secrets step mid-read.
        fs.writeFileSync(file, "NANGO_SECRET_KEY=entered-by-hand\n");
        return { ok: true, stdout: FAKE_SECRET };
      },
      log: rec.log,
      warn: rec.warn,
    });
    expect(result.status).toBe("kept");
    expect(fs.readFileSync(file, "utf8")).toBe("NANGO_SECRET_KEY=entered-by-hand\n");
    expect(rec.all()).not.toContain(FAKE_SECRET);
  });

  it("does nothing when .env.local does not exist", () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "gen-nango-env-"));
    const file = path.join(dir, ".env.local");
    const result = fill({
      envLocalPath: file,
      exec: () => {
        throw new Error("must not run");
      },
    });
    expect(result.status).toBe("no-env-file");
    expect(fs.existsSync(file)).toBe(false);
  });

  it("--quiet silences the status line on stdout (the stderr warning still speaks)", () => {
    const written = makeEnvLocal("# NANGO_SECRET_KEY=\n");
    const recA = recorder();
    fill({
      envLocalPath: written,
      exec: () => ({ ok: true, stdout: FAKE_SECRET }),
      quiet: true,
      log: recA.log,
      warn: recA.warn,
    });
    expect(recA.out).toEqual([]);
    expect(fs.readFileSync(written, "utf8")).toContain(`NANGO_SECRET_KEY=${FAKE_SECRET}`);

    const down = makeEnvLocal("# NANGO_SECRET_KEY=\n");
    const recB = recorder();
    fill({
      envLocalPath: down,
      exec: () => ({ ok: false, stdout: "" }),
      quiet: true,
      log: recB.log,
      warn: recB.warn,
    });
    expect(recB.out).toEqual([]);
    expect(recB.err.join("\n")).toContain("nango-db not reachable — left unset");
  });
});
