// gen-nango-env.mjs — narrow Nango container env generator (cinatra#1691).
//
// WHY THIS EXISTS
// The nango-server docker service encrypts its stored provider secrets with
// NANGO_ENCRYPTION_KEY. The compose file MUST NOT read that secret via
// `environment: NANGO_ENCRYPTION_KEY: "${NANGO_ENCRYPTION_KEY}"` because that
// interpolation resolves the *shell* env (empty on a bare `docker compose
// up`) AND an empty `environment:` value OVERRIDES an `env_file` value on the
// same key — so Nango silently initializes an UNENCRYPTED store (fresh DB) or
// crashes with the misleading "key has been removed" error (existing DB).
// The fix sources the key from a NARROW generated file
// (docker/nango/.nango.env) referenced via `env_file`, with NO overlapping
// `environment:` mapping (the gen-wayflow-env precedent).
//
// These tests pin:
//  1. buildNangoEnv extracts EXACTLY the nango key and reports it missing
//     (no defaults — it is a secret).
//  2. serializeDotenv emits bare KEY=VALUE the compose env_file parser accepts.
//  3. parseDotenv strips quotes (parity with gen-wayflow-env/check-services).
//  4. overlayProcessEnv: non-empty process value wins; empty never clobbers.
//  5. THE COMPOSE NO-OVERLAP INVARIANT: the nango-server service references
//     docker/nango/.nango.env via env_file (required:false) and its
//     `environment:` block does NOT name NANGO_ENCRYPTION_KEY (else the
//     empty-override trap recurs), while the static wiring stays inline.

import { describe, it, expect } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import {
  parseDotenv,
  buildNangoEnv,
  serializeDotenv,
  overlayProcessEnv,
  shouldPreserveExisting,
} from "../gen-nango-env.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../..");

describe("gen-nango-env — parseDotenv", () => {
  it("parses KEY=VALUE and strips surrounding quotes", () => {
    const env = parseDotenv('A=1\nNANGO_ENCRYPTION_KEY="k-123"\n# comment\nBAD LINE\n');
    expect(env).toEqual({ A: "1", NANGO_ENCRYPTION_KEY: "k-123" });
  });
});

describe("gen-nango-env — buildNangoEnv", () => {
  it("extracts exactly NANGO_ENCRYPTION_KEY (ignores everything else)", () => {
    const { env, missing } = buildNangoEnv({
      NANGO_ENCRYPTION_KEY: "k-123",
      BETTER_AUTH_SECRET: "never",
      OPENAI_API_KEY: "never",
      PORT: "3000",
    });
    expect(env).toEqual({ NANGO_ENCRYPTION_KEY: "k-123" });
    expect(missing).toEqual([]);
  });

  it("reports the key missing when absent or whitespace-only (no default — it is a secret)", () => {
    expect(buildNangoEnv({}).missing).toEqual(["NANGO_ENCRYPTION_KEY"]);
    expect(buildNangoEnv({ NANGO_ENCRYPTION_KEY: "   " }).missing).toEqual([
      "NANGO_ENCRYPTION_KEY",
    ]);
  });

  it("trims surrounding whitespace from a kept value", () => {
    expect(buildNangoEnv({ NANGO_ENCRYPTION_KEY: "  k-1  " }).env).toEqual({
      NANGO_ENCRYPTION_KEY: "k-1",
    });
  });
});

describe("gen-nango-env — overlayProcessEnv", () => {
  it("a non-empty process-env value wins over the file", () => {
    const merged = overlayProcessEnv(
      { NANGO_ENCRYPTION_KEY: "file-key" },
      { NANGO_ENCRYPTION_KEY: "proc-key" },
    );
    expect(merged.NANGO_ENCRYPTION_KEY).toBe("proc-key");
  });

  it("an empty/whitespace process value never clobbers a file value", () => {
    const merged = overlayProcessEnv(
      { NANGO_ENCRYPTION_KEY: "file-key" },
      { NANGO_ENCRYPTION_KEY: "   " },
    );
    expect(merged.NANGO_ENCRYPTION_KEY).toBe("file-key");
  });

  it("never reads keys outside the nango set from the process env", () => {
    const merged = overlayProcessEnv({}, { OPENAI_API_KEY: "sneaky" });
    expect(merged).toEqual({});
  });
});

describe("gen-nango-env — shouldPreserveExisting (tolerant-mode clobber guard, codex 1691-r2)", () => {
  it("preserves an existing file that still carries a non-empty key", () => {
    expect(shouldPreserveExisting("# header\nNANGO_ENCRYPTION_KEY=old-key\n")).toBe(true);
  });

  it("does NOT preserve an empty/keyless/absent existing file", () => {
    expect(shouldPreserveExisting("# header only\n")).toBe(false);
    expect(shouldPreserveExisting("NANGO_ENCRYPTION_KEY=   \n")).toBe(false);
    expect(shouldPreserveExisting(undefined)).toBe(false);
  });
});

describe("gen-nango-env — serializeDotenv", () => {
  it("emits bare KEY=VALUE lines under the generated header", () => {
    const text = serializeDotenv({ NANGO_ENCRYPTION_KEY: "k-123" });
    expect(text).toContain("NANGO_ENCRYPTION_KEY=k-123\n");
    expect(text).not.toContain('"k-123"');
    expect(text.startsWith("# GENERATED by scripts/gen-nango-env.mjs")).toBe(true);
  });
});

describe("docker-compose nango-server service — no env_file/environment overlap", () => {
  const composePath = path.join(REPO_ROOT, "docker-compose.yml");
  const yaml = fs.existsSync(composePath) ? fs.readFileSync(composePath, "utf8") : "";

  // Extract the `nango-server:` service block (from `  nango-server:` up to
  // the next top-level 2-space-indented service key). No YAML dep — the
  // gen-wayflow-env.test.mjs convention.
  function nangoBlock() {
    const lines = yaml.split("\n");
    const start = lines.findIndex((l) => /^  nango-server:\s*$/.test(l));
    expect(start).toBeGreaterThanOrEqual(0);
    let end = lines.length;
    for (let i = start + 1; i < lines.length; i++) {
      if (/^  [A-Za-z0-9_-]+:\s*$/.test(lines[i])) {
        end = i;
        break;
      }
    }
    return lines.slice(start, end);
  }

  it("references docker/nango/.nango.env via env_file (required:false)", () => {
    const block = nangoBlock().join("\n");
    expect(block).toMatch(/env_file:/);
    expect(block).toMatch(/path:\s*\.\/docker\/nango\/\.nango\.env/);
    expect(block).toMatch(/required:\s*false/);
  });

  it("has NO environment: NANGO_ENCRYPTION_KEY (the empty-override trap), static wiring stays inline", () => {
    const block = nangoBlock();
    const envStart = block.findIndex((l) => /^    environment:\s*$/.test(l));
    const envKeys = [];
    if (envStart >= 0) {
      for (let i = envStart + 1; i < block.length; i++) {
        const line = block[i];
        if (/^    [A-Za-z0-9_-]+:/.test(line) && !/^      /.test(line)) break;
        const m = line.match(/^      ([A-Z0-9_]+):/);
        if (m) envKeys.push(m[1]);
      }
    }
    expect(envKeys).not.toContain("NANGO_ENCRYPTION_KEY");
    // The static, non-secret wiring must remain inline.
    expect(envKeys).toContain("SERVER_PORT");
    expect(envKeys).toContain("NANGO_DB_HOST");
  });

  it("package.json services script generates the nango env (hard-fail) before compose up", () => {
    const pkg = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "package.json"), "utf8"));
    expect(pkg.scripts.services).toContain("gen-nango-env.mjs --require-encryption-key");
    expect(pkg.scripts.services.indexOf("gen-nango-env.mjs")).toBeLessThan(
      pkg.scripts.services.indexOf("docker compose"),
    );
    // BEFORE `source .env.local` (CodeRabbit 1698-r1): sourcing shell-expands
    // values (a key containing `$…` would be mangled), and the expanded
    // process value would override the raw file value in overlayProcessEnv.
    // The generator parses the file directly, expansion-free.
    expect(pkg.scripts.services.indexOf("gen-nango-env.mjs")).toBeLessThan(
      pkg.scripts.services.indexOf("source .env.local"),
    );
  });
});
