-- #2762 ACCEPTANCE ITEM 2: the stranded state a RETRY CAN ACTUALLY RECOVER.
--
-- Round 5 item 3 asks for proof that a recovery recovers. "Retry activation" is
-- ROW-BOUND AND ACTIVATION-ONLY by design (`packages/extensions/src/actions.ts`,
-- `src/lib/extension-runtime-activate.ts`): it does not reinstall and does not
-- talk to the registry. Its stated premise is a package "whose bytes are fine"
-- but which never registered: "The bytes are already materialized and finalized;
-- only the registration is missing."
--
-- So a retry can only succeed against a row whose install tree EXISTS. That is
-- the one thing the two older fixtures cannot offer: they write a row by SQL for
-- a version that was never installed, so nothing is materialized and the retry
-- correctly refuses with `anchor-refused`. (That refusal is itself captured in
-- this lane, and the app restored the bundled version and said so.)
--
-- This fixture is applied at a different moment than the others. It is NOT
-- seeded before a boot. It is applied to a RUNNING app that has just:
--   1. installed 0.1.5 for real through the marketplace UI, so the bytes are
--      materialized by the PRODUCT and the signature is recorded;
--   2. had that install row archived; and
--   3. been restarted, so only the static bundle registered. The boot log for
--      that run carries NO `RuntimePackageLoader` line, because an archived row
--      is not a candidate — the image's own 0.1.0 is what is serving.
--
-- The single UPDATE below then puts the row back to live WITHOUT registering
-- anything, because a database write is not an activation. It is applied to the
-- running app, with no restart, so nothing gets a chance to activate it.
--
-- The result is exactly the state cinatra#2762 is named for, and the one no
-- earlier fixture could reach: a LIVE, default, marketplace install row whose
-- bytes are on disk, which the running app is NOT serving, while the bundled
-- version is. The settings surface names it "Installed but not in service", and
-- "Retry activation" now has something real to start, so the click can be shown
-- to actually put 0.1.5 into service.
--
-- Addressed by package and source rather than by id, because the row id is
-- generated by the real install and differs on every run.

UPDATE cinatra.installed_extension
   SET status = 'active', is_default = true
 WHERE package_name = '@cinatra-ai/google-appointment-schedules-connector'
   AND source->>'type' = 'verdaccio';
